### ISSUE TITLE
[BUG] Blue skies (Everdawn world, swamp biome) causes crash

### ISSUE THREAD

**Issue by ce-ey-herting** [AMPZNetwork/All-The-Forge-10#1]
## Bug Description
Swamp biome (see screenshot below) in Everdawn world of Blue skies mod causes Minecraft to crash.

## Reproduction Steps
To replicate the problem, follow these steps:
1. Enter red Everdawn portal
2. Fly around the everdawn world
3. swamp biome (see screenshot below) causes Minecraft to crash

## Expected Outcome
Not to crash

## Crash Log (if applicable)

[crash-2023-09-23_17.33.29-client.txt](https://github.com/AMPZNetwork/All-The-Forge-10/files/12706800/crash-2023-09-23_17.33.29-client.txt)

## Screenshots
Affected swamp biome: https://cdn.moddinglegacy.com/742573515409892634-06-07-2021-1623119462.jpg

## Basic Information (please fill in the following details):
 - Operating System: Windows 11
 - All The Forge 10 Version: Version v1.0.2
 - Platform: Technic Launcher
 - Additional Mods Installed: _None_

**Comment by ce-ey-herting** [comment]
When attempting to play in the affected save again, Minecraft crashes again.
Using [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases) I changed the `Dimension` from `blue_skies:everdawn` to `minecraft:overworld`. After that I can join the affected save, but for some reason I'm still in the Everdawn world.

**Comment by ce-ey-herting** [comment]
I just deleted my .minecraft folder, installed Minecraft 1.20.1, installed Forge (forge-1.20.1-47.2.0-installer.jar), then Structure Gel (structure_gel-1.20.1-2.13.1.jar) and Blue Skies (blue_skies-1.20.1-1.3.28.jar).
After that I created a new world, went in the Everdawn world, was able to find the swamp biome and Minecraft did not crash.

**Comment by LabsZero** [comment]
Very strange bug. I will look into a fix for the next update. Thanks for reporting.

**Comment by ce-ey-herting** [comment]
When I copy the broken ATF10 world to my .minecraft folder with its vanilla+forge+structure_gel+blue_skies installation, I get the following error, but no crash:
![vanilla_error](https://github.com/AMPZNetwork/All-The-Forge-10/assets/101746820/975c5531-81f1-41de-94dc-b623a9dddbdc)

**Comment by ce-ey-herting** [comment]
Here is the broken world save: https://drive.google.com/file/d/17Si_DLSJ1BdDUd5itzQUAJ-so2-irxjw/view?usp=sharing

**Comment by LabsZero** [comment]
It seems to be fine on my end (at least with the upcoming patch) so i would recomed installing pack outside the .minecraft folder

**Comment by LabsZero** [comment]
Its also working for me on 1.0.2 using the Technic launcher.

**Comment by ce-ey-herting** [comment]
Okay that's strange.
I also posted the crash report from above to the Blue skies dev's Discord server. David quickly fixed the issue and released a new version: https://legacy.curseforge.com/minecraft/mc-mods/blue-skies/files/4765673

**Comment by LabsZero** [comment]
Great i will update the mod for the next patch

**Comment by ce-ey-herting** [comment]
That's awesome. Thank you very much!
