### ISSUE TITLE
[BUG] ATLauncher All the Forge 10 Update Crash

### ISSUE THREAD

**Issue by RookOberonWolf** [AMPZNetwork/All-The-Forge-10#10]
## Bug Description
Upon updating the All the Forge 10 modpack through the ATLauncher yesterday, February 3, 2024, I was no longer able to access my modded Minecraft. 

## Reproduction Steps
To replicate the problem, 1. Install the newest update to All the Forge 10, 2. While still online, click Play. (There is no discernible difference between Play Online or Play Offline), 3. The crash is immediate. The main launcher window closes, leaving open the side box detailing the logs, and then after a moment or two of wait, everything opens back onto the main launcher window. The system log says it is unable to load, but I was unable to parse what was the main error causing the crash before Minecraft even had a chance to open. This has not happened until the update and I was playing semi-regularly, leading me to believe the update is the source. 

## Expected Outcome
I expected no differences in the usual All the Forge 10 loading processes, but the Minecraft window does not load, even for a flicker of an instant. 

## Crash Log (if applicable)
Crash log independently submitted due to home internet only being computer hotspot and this report being phone based. 

## Screenshots
Not sure what to screenshot other than the prior submitted crash log. Nothing visually happens. 

## Basic Information (please fill in the following details):
 - Operating System: Windows 10
 - All The Forge 10 Version: Latest update as of February 3, 2024
 - Platform: ATLauncher
 - Additional Mods Installed: No additional Mods at this time.

**Comment by LabsZero** [comment]
Try removing Embeddium, Embeddium++ and Oculus mods from your modpack folder. There is a chance its using outdated versions.
