### ISSUE TITLE
Feature request: Chunkloading of any kind

### ISSUE THREAD

**Issue by Devilaux** [AMPZNetwork/All-The-Forge-10#11]
I like the modpack, but I could not find any chunkloaders in the pack. Is there a reason for it? 

Tried adding several myself (not at the same time!) but they all ended crashing during startup. (Tried Chunk Loaders, FTB chunks, Create Power Loader to mention a few)

Any hints or ideas?

**Comment by ghost** [comment]
Mekanism Quantum Entangloporter with Anchor Upgrade

**Comment by Devilaux** [comment]
> Mekanism Quantum Entangloporter with Anchor Upgrade

So basically you need an arc reactor for every "chunkloader" ? (Partially joking, but a hint of seriousness)

**Comment by Devilaux** [comment]
Only chunkloader mod (wich makes sense and is upgradable) that does not crash the pack so far, is "ChunkyMcChunkFace-1.20.1-0.3.4". Just incase others are looking for a solution.

**Comment by burdoto** [comment]
Theres several Chunkloading mechanisms already in:
- AE2: Spatial Anchor will forceload every chunk that contains a part (a simple cable will do) of the attached ME system and use energy for it
- Mekanism: The Anchor upgrade card keeps the chunk in which a block is standing loaded; Works with blocks like the digiminer as well

There's no plans for additional chunkloading solutions.

**Comment by Devilaux** [comment]
> Theres several Chunkloading mechanisms already in:
> 
> * AE2: Spatial Anchor will forceload every chunk that contains a part (a simple cable will do) of the attached ME system and use energy for it
> * Mekanism: The Anchor upgrade card keeps the chunk in which a block is standing loaded; Works with blocks like the digiminer as well
> 
> There's no plans for additional chunkloading solutions.

Thanks for the reply though.

I dont use AE2 and very little of Mekanism. But it's ok, I've added a mod that does the job for me, so you can just close this if that's preferred.
