### ISSUE TITLE
[BUG] All The Forge 10.8.2 instance does not initialize on M1 Mac

### ISSUE THREAD

**Issue by atorrealbaa** [AMPZNetwork/All-The-Forge-10#15]
## Bug Description
All The Forge 10 instance does not open on Apple Silicon (ARM64) Mac, crashes upon clicking play, returns to launcher

## Reproduction Steps
To replicate the problem, follow these steps:
1. Using the ATLauncher, All The Forge 10 10.8.2 instance is created
2. Upon clicking play (online), the instance crashes after a few seconds of loading, no home screen shows up, game does no initialize fully

## Expected Outcome
- Upon following these exact same steps with my Windows PC, this problem does not occur, so I assume it is some incompatibility with the Apple Silicon chip infrastructure

## Crash Log (if applicable)
- File is attached

## Basic Information (please fill in the following details):
 - Operating System: MacOS [Sonoma 14.4.1 (23E224)] [M1 MacBook Pro 16gb]
 - All The Forge Version: 10.8.2
 - Platform: ATLauncher
 - Additional Mods Installed: N/A
 - (I'm not sure if this is the type of problem reported to this page, so no worries if this is outside of the scope, thank you)

**Comment by LabsZero** [comment]
Unfortunately at this time ATLancher itself dose not support M chip Macs so my recommendation is to use some other launcher such as CurseForge or PrismLauncher.

**Comment by atorrealbaa** [comment]
Thank you, the launcher works just fine on M1 macs for other modpacks such as All The Forge 5, Big Chad Guys Plus or All The Mods 9 (probably more this is just a subset of what I have tried), but this could just be a coincidence :)

**Comment by LabsZero** [comment]
Sorry I should of said it only affects 1.20 and newer

**Comment by atorrealbaa** [comment]
Oh that is very helpful, thank you!

**Comment by LabsZero** [comment]
No problem
