### ISSUE TITLE
[REQUEST] Add Refined Storage Addons

### ISSUE THREAD

**Issue by Parker-Bergen** [AMPZNetwork/All-The-Forge-10#16]
## Request Description
AE2 Wireless terminals are available, why shouldn't refined storage wireless crafting grid be added?
This allows both mods to be used and have the same capabilities. This allows anyone to use whichever mod they are more comfortable with using.

## Basic Information (please fill in the following details):
Add Refined Storage Addons

**Comment by burdoto** [comment]
> AE2 Wireless terminals are available, why shouldn't refined storage wireless crafting grid be added?

because RS is a cheap and low effort copycat of AE. if you want the fully blown AE experience, please use AE2.

> This allows both mods to be used and have the same capabilities.

not even remotely; RS does not even come close to the capabilities that AE2 provides. (subnets, p2p, storage interfaces and extreme throughput are only SOME examples)

**Comment by AL1L** [comment]
@burdoto 

https://atlauncher.com/pack/AllTheForge10
![image](https://github.com/AMPZNetwork/All-The-Forge/assets/8514986/d505a020-671d-4ee2-85e2-bf6538c42fa0)

womp womp

You:
![image](https://github.com/AMPZNetwork/All-The-Forge/assets/8514986/a106536a-9379-4cf1-823a-f070177f5fb8)

**Comment by AL1L** [comment]
@LabsZero why would you mark it as invalid, there's no feature request template. You could have just added the feature label. Further, you made no comment as to why it's being closed, which is typically the nice thing to do.

**Comment by burdoto** [comment]
it was closed as invalid because 
A) you posted in the wrong place
B) your argumentation was invalid

also, first and final warning about shitposting. this is not discord.

**Comment by Parker-Bergen** [comment]
Okay, well I would have appreciated if you pointed me in the correct direction to post this request, rather than mark it as invalid and close with no comment; And then have a comment from someone who seems completely unrelated to the development of this mod pack, spout their disagreement to the change, which then proceeded to be implemented a few hours later. - Not because of me but because it was a valid thought and the mod pack maintainers also thought about it, or received a request about it as well prior to my request.

**Comment by burdoto** [comment]
I agree my response wasn't very helpful, however as you can see next to my name it says I'm a member of AMPZ Network.
I did not see the full changelog of the update from yesterday, and since we are planning on dropping RS whatsoever (for the reasons I listed previously), I assumed that the invalid mark would have been it.

For further suggestions, please head to the suggestions part of our forum at ampznetwork.com
