### ISSUE TITLE
[BUG] 'java.io.InterruptedIOException: interrupted' during CurseForge update

### ISSUE THREAD

**Issue by davisharleyr** [AMPZNetwork/All-The-Forge-10#17]
## Bug Description
Please provide a concise description of the issue you're experiencing.

## Reproduction Steps
To replicate the problem, follow these steps:
1. Navigate to '...'
4. Observe the error

## Expected Outcome
Explain what you anticipated should happen in detail.

## Crash Log (if applicable)
https://paste.atlauncher.com/view/bbaa64c5-ab00-4b6d-87db-cd1dd89c5df8

## Screenshots
If relevant, include screenshots to aid in explaining the issue.

## Basic Information (please fill in the following details):
 - Operating System: [e.g., Windows]
 - All The Forge Version: [e.g., 5.4]
 - Platform: [e.g., atlauncher]
 - Additional Mods Installed: [e.g., Optifine]

**Comment by LabsZero** [comment]
Issue looks to be curseforge side try download it again.

**Comment by davisharleyr** [comment]
I've re-installed and the problem is still arising. My game won't even open before crashing.

**Comment by burdoto** [comment]
please fill out at least the "basic information" area of the issue template.


    Operating System: [e.g., Windows]
    All The Forge Version: [e.g., 5.4]
    Platform: [e.g., atlauncher]
    Additional Mods Installed: [e.g., Optifine]
