### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Krupiz** [AMPZNetwork/All-The-Forge-10#20]
## Bug Description
0 fps / constant stuttering when joining multiplayer server, it doesn't depend on number of players on server.
Happened to one person from 6 playing on private server.

## Reproduction Steps
To replicate the problem, follow these steps:
1. Join any server
2. Load into world and it will occur.
3. Observe the error

## Expected Outcome
When you join the server it just makes your game go 0 fps, it doesn't happen in singleplayer on the same machine. 

## Found Fix (at least that worked for this scenario)
The faulty thing is CraterLib being in version 2.0.0. Using mod "Spark" I found out that this mod was causing a huge tick ms which led to clients machine lag. Just updating it to 2.0.1 fixes it because as it was mentioned in it's changelog:
- Removed the server pinger call, which causes lag with Simple RPC on Direct connections/lan - Fixes [#88](https://github.com/hypherionmc/simple-rpc-public/issues/88)

Side note:
After updating game was running very smoothly (above 60 fps)

## Basic Information (please fill in the following details):
 - Operating System: Windows
 - All The Forge Version: 10.11
 - Platform: Prism launcher and later curseforge
 - Additional Mods Installed: create deco

**Comment by LabsZero** [comment]
Thank you for reporting this bug. I will push out a hot fix asap.

**Comment by LabsZero** [comment]
Issue has been fixed in 10.12. Thank you for reporting this.
