### ISSUE TITLE
Same recipe

### ISSUE THREAD

**Issue by Wraithypooo** [AMPZNetwork/All-The-Forge-10#21]
## Basic Information (please complete the following):
- Win10
- ATF 10
- ATLauncher
- Trashbin and Chunkloader

## Bug Description
Impaler and sweeping edge has same recipe in enderio enchanter

## Expected Behavior
I expected to get sweeping edge enchantment, but could only get impaler

### Confirmation

 [X] I have confirmed that All The Forge is up to date.
 [X] I have checked that no other mods are causing the issue.
 [X] I have searched the existing issues to ensure this is not a duplicate.
 [X] I have provided the necessary information above to help reproduce this issue.

**Comment by burdoto** [comment]
EnderIO is still in beta, there may be some issues. Please report this to the EnderIO team directly here: https://github.com/Team-EnderIO/EnderIO
