### ISSUE TITLE
shaders

### ISSUE THREAD

**Issue by vvampyr** [AMPZNetwork/All-The-Forge-10#22]
## Basic Information (please complete the following):
- **Operating System:** [e.g., Windows]
- **All The Forge Version:** [e.g., 11.0]
- **Platform:** [e.g., ATLauncher]
- **Additional Mods Installed:** [e.g., Optifine]

## Bug Description
Provide a clear and concise description of the issue.

## Steps to Reproduce
To reproduce the issue, follow these steps:
1. Navigate to '...'
2. Click on '...'
3. Scroll down to '...'
4. Observe the error

## Expected Behavior
Describe what you expected to happen.

## Crash Log (if applicable)
If the bug causes a crash, attach or drag and drop the crash log here.

<details>
<summary>Crash Log</summary>
<pre>
[Paste your crash log here]
</pre>
</details>

### Confirmation

- [X] I have confirmed that All The Forge is up to date.
- [X] I have not modified the pack.
- [X] I have checked that no other mods are causing the issue.
- [X] I have searched the existing issues to ensure this is not a duplicate.
- [X] I have provided the necessary information above to help reproduce this issue.

**Comment by burdoto** [comment]
since you didn't fill out the template, we dont know what we can do for you.
