### ISSUE TITLE
[BUG] Sleeping bag uncraftable - shares recipe with wool slabs

### ISSUE THREAD

**Issue by romulous75** [AMPZNetwork/All-The-Forge-10#3]
## Bug Description
Sleeping bag [Comforts mod] uncraftable - shares recipe with wool slabs [Absent By Design mod]

## Reproduction Steps
To replicate the problem, follow these steps:
1. Try to craft the sleeping bag with three horizontal wool [ x x x ]

## Expected Outcome
Able to pull a sleeping bag out

## Basic Information (please fill in the following details):
 - O/S Windows 10
 - All The Forge 10 Version: 1.2.0
 - Platform: MultiMC
 - Additional Mods Installed: N/A

**Comment by LabsZero** [comment]
You should be able to still craft the recapie by clicking icon shown in the image below.
![image](https://github.com/AMPZNetwork/All-The-Forge-10/assets/12278357/bae5e149-b7e2-4cfe-b0fb-8e57ee031569)

**Comment by romulous75** [comment]
You are correct. Did not see that.
