### ISSUE TITLE
[BUG] You Keep Your Inventory With No Gravestone If You Die in Modded Dimensions

### ISSUE THREAD

**Issue by Radiounactive** [AMPZNetwork/All-The-Forge-10#5]
## Bug Description
If you die in a modded dimension (one that is not in vanilla Minecraft) you keep your inventory and you do not get a grave stone. This ruins some of the danger of the other dimensions.

## Reproduction Steps
To replicate the problem, follow these steps:
1. Spawn
2. Build aether, Twilight, everbright, everdawn, or other non vanilla dimension portal.
3. Go through 
4. Die.
5. Notice that you keep inventory and do not get grave stone.

## Basic Information (please fill in the following details):
 - Windows
 - All The Forge 10 Version: 1.3.0
 - Platform: coursed forge
 - Additional Mods Installed: none

**Comment by LabsZero** [comment]
Thank you for your reporting. I will see what i can do to get this fixed for the next patch.

**Comment by LabsZero** [comment]
Issue has been resoved in the upcoming patch 1.5.0.
