### ISSUE TITLE
[BUG] Extreme reactors production is very low

### ISSUE THREAD

**Issue by Radiounactive** [AMPZNetwork/All-The-Forge-10#6]
## Bug Description
Please provide a concise description of the issue you're experiencing.

## Reproduction Steps
To replicate the problem, follow these steps:
Build 7x7 reactor with diamond blocks as coolant and fuel rodes as checker pattern

## Expected Outcome
You get about 40krf/t and if you are generating steam you get 59mlb/t of steam.

This produces like 3krf/t in a 5x5x10 turbine.

NOTE:

I see in the config the multiplyer is set to 4/10.. that is what other mods are set to as well. Except with the same reactors they get like 200krf/t and get about 1000mlb/t of steam (if you are generating steam)

This makes extreme generators no where near "extreme." They produce less than a couple wind generators and take 10000x the cost. Not only that but they take uranium to run. This should definitely be fixed to make extreme reactors worth it 

## Basic Information (please fill in the following details):
 - Operating System: windows 10
 - All The Forge 10 Version: 4.0
 - Platform: Atlauncher
 - Additional Mods Installed: various server optimization mods

**Comment by burdoto** [comment]
We had adjusted default configuration shipped with 1.5, please try cleaning up configs if desirable and updating. Please let us know if you're still having this issue.
