### ISSUE TITLE
[BUG] Slime is being produced as coolant in turbines instead of water 

### ISSUE THREAD

**Issue by Radiounactive** [AMPZNetwork/All-The-Forge-10#7]
## Bug Description
Please provide a concise description of the issue you're experiencing.

## Reproduction Steps
To replicate the problem, follow these steps:
1. Create extreme reactors reactor
2. Create turbine
3. Hook turbine and reactor together
4. Watch as steam is condensed to "fluid.type.create.slime.(something).(something)"

## Expected Outcome
Instead of water condensing in the turbine you are greeted with the seemingly very glitched out "fluid.type.create.slime.(something).(something)" 

This breaks turbines as it is not able to be reused

## Crash Log (if applicable)
If the bug triggers a crash, please include or link the crash log here.

## Screenshots
If relevant, include screenshots to aid in explaining the issue.

## Basic Information (please fill in the following details):
 - Operating System: windows 10
 - All The Forge 10 Version: 4.0
 - Platform: Atlauncher 
 - Additional Mods Installed: several server side optimization mods

**Comment by burdoto** [comment]
i have also noticed this happening, although not rendering turbines completely unusable to me
how is your turbine configured?
