### ISSUE TITLE
[BUG] Items in additional slots are duplicating

### ISSUE THREAD

**Issue by geqo** [AMPZNetwork/All-The-Forge-10#8]
## Bug Description
Upon destroying a character's grave and collecting loot, items in additional slots are being duplicated. Tested with the backpack and engineer's goggles. The contents of the backpack are not duplicated.
Wearable items do not equip automatically. Not sure if it's a bug, but just wanted to mention it just in case

## Reproduction Steps
To replicate the problem, follow these steps:
1. Equip engineering googles and sophisticated backpack
2. Die
3. Go to grave
4. Destroy the grave

## Expected Outcome
Exact same loot

## Screenshots
![Screenshot 2024-01-15 004227](https://github.com/AMPZNetwork/All-The-Forge-10/assets/17268505/b8d9b209-4f70-46e7-9d7f-515cca65d7ea)

## Basic Information (please fill in the following details):
 - Operating System: [e.g., Windows]
 - All The Forge 10 Version: 1.5.0
 - Platform: I don't know, just this modpack
 - Additional Mods Installed: OreExcavation, CarryOn

**Comment by ToxesFoxes** [comment]
same, idk what mod creates that stupid grave

**Comment by ToxesFoxes** [comment]
I found that "mod" (datapack) at `All The Forge 10\minecraft\config\openloader\data\ketkets-graves-v1-XXXXX.zip`

**Comment by LabsZero** [comment]
Nothing we can do without removing the graves datapack and if we was to it will cause more issues then its worth. This should not be a problem in All The Forge v11 when that is released.
