### ISSUE TITLE
[BUG] Crash due to a ClassCastException in the "Exception in server tick loop" after 1.5.0 update.

### ISSUE THREAD

**Issue by evans901** [AMPZNetwork/All-The-Forge-10#9]
## Bug Description
After updating to 1.5.0 from 1.4.0 my server is experiencing random crashes. 

## Reproduction Steps
No clear way to reproduce the error. Happens at random. Looking at the crash log I believe create trains are causing the issue.

## Crash Log (if applicable)
[crash-2024-01-20_08.16.40-server.txt](https://github.com/AMPZNetwork/All-The-Forge-10/files/13998591/crash-2024-01-20_08.16.40-server.txt)

## Basic Information (please fill in the following details):
 - Operating System: Linux? (Host Havoc Server)
 - All The Forge 10 Version: 1.5.0
 - Platform: ATLauncer / Host Havoc Server
 - Additional Mods Installed: N/A

**Comment by LabsZero** [comment]
Your going to have to report this issue to devs in order for them to create a patch for us to apply to the pack.
https://github.com/Creators-of-Create/Create/issues
